name: Java CI with Maven for backend sprint1

on:
  push:
    branches: [ "back-end-dev-sprint1" ]
  pull_request:
    branches: [ "back-end-dev-sprint1"]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: yw
          MYSQL_USER: root
          MYSQL_PASSWORD: 123456
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        working-directory: './backend'
        run: mvn -B package --file pom.xml
        env:
          DATABASE_URL: jdbc:mysql://localhost:3306/yw
          DATABASE_USERNAME: root
          DATABASE_PASSWORD: 123456