name: Java CI with Maven for backend sprint1

on:
  push:
    branches: [ "back-end-dev-sprint1" ]
  pull_request:
    branches: [ "back-end-dev-sprint1"]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Build and Test with Maven
        working-directory: './backend'
        env:
          DB_HOST: 127.0.0.1  # Your local mysql login info
          DB_PORT: 3306
          DB_NAME: yw
          DB_USER: root
          DB_PASS: 123456
        run: mvn -B package test --file pom.xml
