name: Backend CI

on:
  push:
    branches: [ "back-end-master","main","back-end-dev-sprint[0-9]+"]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: yw
          MYSQL_USER: githubCI
          MYSQL_PASSWORD: 123456
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

#      - name: Wait for MySQL to be ready
#        run: |
#          while ! mysqladmin ping -h localhost -u root -p123456 --silent; do
#            echo "Waiting for MySQL to start..."
#            sleep 2
#          done

      - name: Run Flyway Migrations
        working-directory: './backend'
        run: mvn -B flyway:migrate
        env:
          FLYWAY_URL: jdbc:mysql://localhost:3306/yw
          FLYWAY_USER: root
          FLYWAY_PASSWORD: 123456

      - name: Build with Maven
        working-directory: './backend'
        run: mvn -B package --file pom.xml
        env:
          DATABASE_URL: jdbc:mysql://localhost:3306/yw
          DATABASE_USERNAME: root
          DATABASE_PASSWORD: 123456